other config directory: config
other config files:
  - scripts optimised.yaml
  - sites.yaml
  - testing.yaml
  - pagerank.yaml
days till next page check: 5
seconds between scraping on same site: 3
daemon wait time seconds: 600
threaded server handling: yes
ignore url fragments: yes
threading timeout: 60 # assign null to ignore
results per search: 10

site request interval seconds: 5
site requests in interval: 3

global request interval seconds: 10
global requests in interval: 80