other config files:
  - scripts.yaml
  - sites.yaml
  - testing.yaml
days till next page check: 5
seconds between scraping on same site: 3
daemon wait time seconds: 600
threaded server handling: yes
ignore url fragments: yes
pagerank interval seconds: 10
default page rank: 100
page rank multiplier: 1
page rank interval seconds: 5
page rank memory rows: 20