script folder: sqlite scripts
database folder: db

init script: webdbinit.sql
database name: webscrape.db

# for automatic init script updates
hash script: autohash.sql
hash insert: inserthash.sql
hash check: checkhash.sql

# crawler
get link: getlink.sql
insert link: insertlink.sql
insert token: inserttoken.sql
find old links: daemon.sql
insert page link: insertconnection.sql
time check link: timecheck.sql
insert many page link: insertmanyconnection.sql
insert many token: insertmanytoken.sql
ensure token exists: ensuretoken.sql

# pagerank
get backlinks pagerank: getbacklinks.sql
get subdomains: getsubdomains.sql
set temporary subdomain rank:  setrank.sql
migrate subdomain ranks: migraterank.sql
get subdomain count: subdomaincount.sql
get total rank: totalrank.sql

# search
get query subdomains: find_subdomains_with_tokens.sql
get subdomain tokens: get_subdomain_tokens.sql