production: no

# sql
auto reset on db init changes: yes
print sql commands: no
allow duplicates despite timing: no
execute many: yes # should be yes by default only set to no for testing

# logging
log file path: logs/trace.log
enable logging profiler: no
only log relative calls: yes
ignore internal calls: yes
logging interval: 60
track database times: no

ignore names:
  - tokens
  - targets
# set to all to log all, otherwise a list of thread names should be given
allowed threads:
  - pagerank_daemon
  - site_handler
  - handle_queries

# pagerank
log total pagerank: yes
track pagerank times: no
track pagerank backlinks: no